name: Package GEDKeeper3 for Fedora

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Debug
      run: apt install rpmbuild
    - name: Debug
      run: dotnet sdk check
    - name: Build
      run: dotnet build -c Linux_Release --runtime linux-x64 --output ./GEDKeeper3/release
      working-directory: projects/GKv3
    - name: Debug
      run: du -d1 -h projects/GKv3/GEDKeeper3/
    - name: Debug
      run: ls -laR projects/GKv3/GEDKeeper3/release

