name: Package GEDKeeper3 for Fedora

on:
  push:
    branches:
      - separate-build-fedora
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOTNET_VERSION: '6.0.*'

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: .NET SDK check
      run: dotnet sdk check
# error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'freebsd-x64'
# https://learn.microsoft.com/en-us/dotnet/devops/dotnet-build-github-action
#    - name: Install dependencies
#      run: dotnet restore
#      working-directory: projects/GKv3
    - name: Build
      run: dotnet build -c Linux_Debug
      # run: dotnet build -c Linux_Release
      working-directory: projects/GKv3
    - name: Get latest tag
      uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true
        with_initial_version: true
        initial_version: '1.0.0'
    - name: Package
      run: rpmbuild --build-in-place --define "gh_version ${{ steps.get-latest-tag.outputs.tag }}" -bb deploy/rpm/gedkeeper-gh-act.spec
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: gedkeeper3-rpm
        path: ~/rpmbuild/RPMS/x86_64/*.rpm
        if-no-files-found: error
