name: Package GEDKeeper3 for Fedora

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '6.0.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Debug
      run: dotnet sdk check
    - name: Install dependencies
      run: dotnet restore
      working-directory: projects/GKv3
    - name: Build
      run: dotnet build -c Linux_Release --no-restore
      working-directory: projects/GKv3
    - name: Debug
      run: du -d1 -h
    - name: Package
      run: bash ./gk_linux_rpm_fedora_package.sh
      working-directory: deploy
